[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
irc = {path = "../irc"}
tokio = { version = "1.36", features = ["full"] }
crossterm = "0.27.0"
